version: "3.8"

services:
  # --- Products Service ---
  db:
    image: postgres:15-alpine
    container_name: postgres_product_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER} # Explicitly use user for username
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: product
    ports:
      - "5435:5432"
    volumes:
      - products_db_data:/var/lib/postgresql/data
    healthcheck: # Tells Docker when the DB is genuinely awake
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d product"]
      interval: 5s
      timeout: 5s
      retries: 5

  products-service:
    build: ./products-service
    container_name: app_products
    restart: always
    ports:
      - "8001:8000"
    environment:
      PRODUCT_DATABASE_URL: ${PRODUCT_DATABASE_URL}
    volumes:
      - ./products-service:/app
    depends_on:
      db:
        condition: service_healthy
  # --- Orders Service ---
  orders_db:
    image: postgres:15-alpine
    container_name: postgres_order_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER} # Explicitly use user for username
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: order
    ports:
      - "5436:5432"
    volumes:
      - orders_db_data:/var/lib/postgresql/data
    healthcheck: # Tells Docker when the DB is genuinely awake
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d order"]
      interval: 5s
      timeout: 5s
      retries: 5

  orders-service:
    build: ./orders-service
    container_name: app_orders
    restart: always
    ports:
      - "8002:8000"
    environment:
      ORDER_DATABASE_URL: ${ORDER_DATABASE_URL}
    volumes:
      - ./orders-service:/app
    depends_on:
      orders_db:
        condition: service_healthy

volumes:
  products_db_data:
  orders_db_data:
